[package]
name = "prime-wasm"
version = "0.1.2"
authors = ["yannDuval <yann.duval@gmx.fr>"]
edition = "2018"
description = "A module looking for prime numbers"
license = "MIT/Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.19"